---
# Login to vmanage and get cookie.  Store in variable
- name: Check routing table
  hosts: all
  connection: local
  tasks:
    - name: OBTAIN SESSION COOKIE
      uri:
        url: https://{{ inventory_hostname }}:8443/j_security_check
        method: POST
        body:
          j_username: "{{ username }}"
          j_password: "{{ password }}"
        body_format: form-urlencoded
        validate_certs: no
      register: login_data

# Step 1 - GET ROUTING TABLE USING URI METHOD
    - name: Check routing table with URI module
      uri:
        url: https://{ inventory_hostname }}:8443/dataservice/device/ip/routetable?deviceId={{ device_ip }}
        headers:
          Cookie: "{{ login_data.set_cookie }}"
        body_format: json
        return_content: yes
        validate_certs: no
      vars:
        device_ip: 172.27.0.11
      register: routing_data

    - name: Print Routing Data
      debug:
        var: routing_data

# Step 2 - COUNT NUMBER OF ROUTES
    - name: Count the number of routes
      debug:
        msg: "Routing table has {{ routing_data.json.data | length }} routes"

# Step 3 - GET POLICY FACTS USING SDK
    - name: Check policy configurations
      hosts: all
      connection: local
      roles:
        - python-viptela
      tasks:
        - name: GET POLICY LISTS
          vmanage_policy_list_facts:
            host: "{{ inventory_hostname }}"
            user: "{{ username }}"
            password: "{{ password }}"
          no_log: yes
          register: list_facts

        - name: Print Policy Lists
          debug: var=list_facts.policy_lists
          